export const HEADER_HEIGHT = 60;

export const CARBOHYDRATES_CALORIES_FACTOR = 4;
export const FATS_CALORIES_FACTOR = 9;
export const PROTEIN_CALORIES_FACTOR = 4;

export const CARBOHYDRATES_HIGH_BREAKPOINT = 0.7;
export const CARBOHYDRATES_LOW_BREAKPOINT = 0.25;
export const FATS_HIGH_BREAKPOINT = 0.35;
export const FATS_LOW_BREAKPOINT = 0.25;
export const PROTEINS_HIGH_BREAKPOINT = 0.3;
export const PROTEINS_LOW_BREAKPOINT = 0.08;
